language: generic

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.deb
  - sudo dpkg -i hugo_0.46_Linux-64bit.deb

install:
  - hugo env
  - hugo
